function dphids = dPHIds(dx,dy,mu,kappa,alpha,u1,u2,u3,u4,u5,u6,u7,u8,p1,p2,p3,p4,T1,T2,T3,T4)
%dPHIds
%    DPHIDS = dPHIds(DX,DY,MU,KAPPA,ALPHA,U1,U2,U3,U4,U5,U6,U7,U8,P1,P2,P3,P4,T1,T2,T3,T4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-06-04 16:11:32

%Version: 1.0 with Energy
mt1 = [(mu.*(u2-u4-u6+u8))./4.0+(dy.*(mu.*u1.*2.4e+1-mu.*u3.*2.4e+1-mu.*u5.*1.2e+1+mu.*u7.*1.2e+1+alpha.*dx.^2.*u1.*4.0+alpha.*dx.^2.*u3.*2.0+alpha.*dx.^2.*u5+alpha.*dx.^2.*u7.*2.0))./(dx.*3.6e+1)+(dx.*mu.*(u1.*2.0+u3-u5-u7.*2.0))./(dy.*6.0);(mu.*(u1+u3-u5-u7))./4.0+(dy.*(mu.*u2.*1.2e+1-mu.*u4.*1.2e+1-mu.*u6.*6.0+mu.*u8.*6.0+alpha.*dx.^2.*u2.*4.0+alpha.*dx.^2.*u4.*2.0+alpha.*dx.^2.*u6+alpha.*dx.^2.*u8.*2.0))./(dx.*3.6e+1)+(dx.*mu.*(u2.*2.0+u4-u6-u8.*2.0))./(dy.*3.0)];
mt2 = [(mu.*(u2-u4-u6+u8))./4.0+(dy.*(mu.*u1.*-2.4e+1+mu.*u3.*2.4e+1+mu.*u5.*1.2e+1-mu.*u7.*1.2e+1+alpha.*dx.^2.*u1.*2.0+alpha.*dx.^2.*u3.*4.0+alpha.*dx.^2.*u5.*2.0+alpha.*dx.^2.*u7))./(dx.*3.6e+1)+(dx.*mu.*(u1+u3.*2.0-u5.*2.0-u7))./(dy.*6.0);mu.*(u1+u3-u5-u7).*(-1.0./4.0)+(dy.*(mu.*u2.*-1.2e+1+mu.*u4.*1.2e+1+mu.*u6.*6.0-mu.*u8.*6.0+alpha.*dx.^2.*u2.*2.0+alpha.*dx.^2.*u4.*4.0+alpha.*dx.^2.*u6.*2.0+alpha.*dx.^2.*u8))./(dx.*3.6e+1)+(dx.*mu.*(u2+u4.*2.0-u6.*2.0-u8))./(dy.*3.0)];
mt3 = [mu.*(u2-u4-u6+u8).*(-1.0./4.0)+(dy.*(mu.*u1.*-1.2e+1+mu.*u3.*1.2e+1+mu.*u5.*2.4e+1-mu.*u7.*2.4e+1+alpha.*dx.^2.*u1+alpha.*dx.^2.*u3.*2.0+alpha.*dx.^2.*u5.*4.0+alpha.*dx.^2.*u7.*2.0))./(dx.*3.6e+1)-(dx.*mu.*(u1+u3.*2.0-u5.*2.0-u7))./(dy.*6.0)];
mt4 = [mu.*(u1+u3-u5-u7).*(-1.0./4.0)+(dy.*(mu.*u2.*-6.0+mu.*u4.*6.0+mu.*u6.*1.2e+1-mu.*u8.*1.2e+1+alpha.*dx.^2.*u2+alpha.*dx.^2.*u4.*2.0+alpha.*dx.^2.*u6.*4.0+alpha.*dx.^2.*u8.*2.0))./(dx.*3.6e+1)-(dx.*mu.*(u2+u4.*2.0-u6.*2.0-u8))./(dy.*3.0)];
mt5 = [mu.*(u2-u4-u6+u8).*(-1.0./4.0)+(dy.*(mu.*u1.*1.2e+1-mu.*u3.*1.2e+1-mu.*u5.*2.4e+1+mu.*u7.*2.4e+1+alpha.*dx.^2.*u1.*2.0+alpha.*dx.^2.*u3+alpha.*dx.^2.*u5.*2.0+alpha.*dx.^2.*u7.*4.0))./(dx.*3.6e+1)-(dx.*mu.*(u1.*2.0+u3-u5-u7.*2.0))./(dy.*6.0)];
mt6 = [(mu.*(u1+u3-u5-u7))./4.0+(dy.*(mu.*u2.*6.0-mu.*u4.*6.0-mu.*u6.*1.2e+1+mu.*u8.*1.2e+1+alpha.*dx.^2.*u2.*2.0+alpha.*dx.^2.*u4+alpha.*dx.^2.*u6.*2.0+alpha.*dx.^2.*u8.*4.0))./(dx.*3.6e+1)-(dx.*mu.*(u2.*2.0+u4-u6-u8.*2.0))./(dy.*3.0);0.0;0.0;0.0;0.0;(dx.*(T1.*kappa.*2.0+T2.*kappa-T3.*kappa-T4.*kappa.*2.0))./(dy.*6.0)+(dy.*(T1.*kappa.*1.2e+1-T2.*kappa.*1.2e+1-T3.*kappa.*6.0+T4.*kappa.*6.0))./(dx.*3.6e+1)];
mt7 = [(dx.*(T1.*kappa+T2.*kappa.*2.0-T3.*kappa.*2.0-T4.*kappa))./(dy.*6.0)-(dy.*(T1.*kappa.*1.2e+1-T2.*kappa.*1.2e+1-T3.*kappa.*6.0+T4.*kappa.*6.0))./(dx.*3.6e+1);(dx.*(T1.*kappa+T2.*kappa.*2.0-T3.*kappa.*2.0-T4.*kappa).*(-1.0./6.0))./dy-(dy.*(T1.*kappa.*6.0-T2.*kappa.*6.0-T3.*kappa.*1.2e+1+T4.*kappa.*1.2e+1))./(dx.*3.6e+1);(dx.*(T1.*kappa.*2.0+T2.*kappa-T3.*kappa-T4.*kappa.*2.0).*(-1.0./6.0))./dy+(dy.*(T1.*kappa.*6.0-T2.*kappa.*6.0-T3.*kappa.*1.2e+1+T4.*kappa.*1.2e+1))./(dx.*3.6e+1)];
dphids = [mt1;mt2;mt3;mt4;mt5;mt6;mt7];
end
