function dphidg = dPHIdg(dx,dy,mu,kappa,alpha,dalpha,u1,u2,u3,u4,u5,u6,u7,u8,p1,p2,p3,p4,T1,T2,T3,T4)
%dPHIdg
%    DPHIDG = dPHIdg(DX,DY,MU,KAPPA,ALPHA,DALPHA,U1,U2,U3,U4,U5,U6,U7,U8,P1,P2,P3,P4,T1,T2,T3,T4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-06-04 16:11:32

%Version: 1.0 with Energy
dphidg = (dalpha.*dx.*dy.*(u1.*u3.*2.0+u1.*u5+u2.*u4.*2.0+u1.*u7.*2.0+u2.*u6+u3.*u5.*2.0+u2.*u8.*2.0+u3.*u7+u4.*u6.*2.0+u4.*u8+u5.*u7.*2.0+u6.*u8.*2.0+u1.^2.*2.0+u2.^2.*2.0+u3.^2.*2.0+u4.^2.*2.0+u5.^2.*2.0+u6.^2.*2.0+u7.^2.*2.0+u8.^2.*2.0))./3.6e+1;
end
