function phi = PHI(dx,dy,mu,kappa,alpha,u1,u2,u3,u4,u5,u6,u7,u8,p1,p2,p3,p4,T1,T2,T3,T4)
%PHI
%    PHI = PHI(DX,DY,MU,KAPPA,ALPHA,U1,U2,U3,U4,U5,U6,U7,U8,P1,P2,P3,P4,T1,T2,T3,T4)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2025-06-03 15:35:24

%Version: 1.0 with Energy
et1 = T1.^2.*kappa.*6.0+T2.^2.*kappa.*6.0+T3.^2.*kappa.*6.0+T4.^2.*kappa.*6.0+mu.*u1.^2.*1.2e+1+mu.*u2.^2.*6.0+mu.*u3.^2.*1.2e+1+mu.*u4.^2.*6.0+mu.*u5.^2.*1.2e+1+mu.*u6.^2.*6.0+mu.*u7.^2.*1.2e+1+mu.*u8.^2.*6.0+alpha.*dx.^2.*u1.^2.*2.0+alpha.*dx.^2.*u2.^2.*2.0+alpha.*dx.^2.*u3.^2.*2.0+alpha.*dx.^2.*u4.^2.*2.0+alpha.*dx.^2.*u5.^2.*2.0+alpha.*dx.^2.*u6.^2.*2.0+alpha.*dx.^2.*u7.^2.*2.0+alpha.*dx.^2.*u8.^2.*2.0-T1.*T2.*kappa.*1.2e+1-T1.*T3.*kappa.*6.0+T1.*T4.*kappa.*6.0+T2.*T3.*kappa.*6.0-T2.*T4.*kappa.*6.0-T3.*T4.*kappa.*1.2e+1-mu.*u1.*u3.*2.4e+1-mu.*u1.*u5.*1.2e+1;
et2 = mu.*u2.*u4.*-1.2e+1+mu.*u1.*u7.*1.2e+1-mu.*u2.*u6.*6.0+mu.*u3.*u5.*1.2e+1+mu.*u2.*u8.*6.0-mu.*u3.*u7.*1.2e+1+mu.*u4.*u6.*6.0-mu.*u4.*u8.*6.0-mu.*u5.*u7.*2.4e+1-mu.*u6.*u8.*1.2e+1+alpha.*dx.^2.*u1.*u3.*2.0+alpha.*dx.^2.*u1.*u5+alpha.*dx.^2.*u2.*u4.*2.0+alpha.*dx.^2.*u1.*u7.*2.0+alpha.*dx.^2.*u2.*u6+alpha.*dx.^2.*u3.*u5.*2.0+alpha.*dx.^2.*u2.*u8.*2.0+alpha.*dx.^2.*u3.*u7+alpha.*dx.^2.*u4.*u6.*2.0+alpha.*dx.^2.*u4.*u8+alpha.*dx.^2.*u5.*u7.*2.0+alpha.*dx.^2.*u6.*u8.*2.0;
et3 = (dy.*(et1+et2))./(dx.*3.6e+1)+(dx.*(T1.^2.*kappa+T2.^2.*kappa+T3.^2.*kappa+T4.^2.*kappa+mu.*u1.^2+mu.*u2.^2.*2.0+mu.*u3.^2+mu.*u4.^2.*2.0+mu.*u5.^2+mu.*u6.^2.*2.0+mu.*u7.^2+mu.*u8.^2.*2.0+T1.*T2.*kappa-T1.*T3.*kappa-T1.*T4.*kappa.*2.0-T2.*T3.*kappa.*2.0-T2.*T4.*kappa+T3.*T4.*kappa+mu.*u1.*u3-mu.*u1.*u5+mu.*u2.*u4.*2.0-mu.*u1.*u7.*2.0-mu.*u2.*u6.*2.0-mu.*u3.*u5.*2.0-mu.*u2.*u8.*4.0-mu.*u3.*u7-mu.*u4.*u6.*4.0-mu.*u4.*u8.*2.0+mu.*u5.*u7+mu.*u6.*u8.*2.0))./(dy.*6.0);
et4 = (mu.*(u1+u3-u5-u7).*(u2-u4-u6+u8))./4.0;
phi = et3+et4;
end
